### ISSUE TITLE
enter invalid pwd/password, still be able to login

### ISSUE THREAD

**Issue by lixphilosophy** [shared-systems/api#17]
I enter a invalid password for my account 'test@test.com' and the application still let me to login.

I print out the information in the attempt_login function right after the api post function. The return value is shown as following:

200 {'success': True, 'error': None, 'message': 'Login successful', 'token': '', 'auth': True}

**Comment by samgomena** [comment]
What was the password you used?

**Comment by lixphilosophy** [comment]
Just some random input, either one would work

**Comment by lixphilosophy** [comment]
I think it’s not the api problem but the backend

**Comment by samgomena** [comment]
When you say 'api' are you referring to the server or the module in PLUTO called `api.py`? Also, it doesn't grant authentication by way of not returning a JWT. However, it does return a misleading message stating that authentication has been granted. Regardless, I'm working on a fix for it right now.
