### ISSUE TITLE
wiki page endpoint return value

### ISSUE THREAD

**Issue by lixphilosophy** [shared-systems/api#33]
It might be a better idea to identify the return value from if the call is success.

**Comment by samgomena** [comment]
It should outline the structure of the response that is returned. Is there a specific example you're referring to? (And if so, can you add a link to it!)

**Comment by lixphilosophy** [comment]
There are some section present the response package sample (i.e. [Account](https://github.com/deepmarket/api/wiki/API-Enpoints#response-1)). I consider it would be better if we also have this kind of sample for `resources` and `jobs` section.

**Comment by samgomena** [comment]
Oh, as in the documentation is missing? If so, yes, it's still a work in progress! (I'm actually trying to automate it so we won't have to worry about this sort of stuff anymore.) For the time being, you can look at the model and controller files to get a better idea of what's being returned!

**Comment by lixphilosophy** [comment]
Then I think it would be fine. I have read the controller file already. I just wonder if later on the new person joined the team, and he could get a better instruction. It should be fine if this is in your implementation checklist.
