### ISSUE TITLE
Update myscript.py filename

### ISSUE THREAD

**Issue by samgomena** [shared-systems/api#4]
@amarjitjadhav Can you name the file `myscript.py` something more germane to what it does.

**Comment by amarjitjadhav** [comment]
sure.. will change..

**Comment by amarjitjadhav** [comment]
M not able to find myscript.py. But do you mean the file I added to task scheduler to generate automatic prices every day?

**Comment by samgomena** [comment]
It looks like myscript is responsible for price generation, yes. And it’s in the main directory of this repo... Maybe you’re on the wrong branch?
