### ISSUE TITLE
login issue

### ISSUE THREAD

**Issue by lixphilosophy** [shared-systems/api#6]
when node app.js is launch but mongodb (either server port or client port) is not, pluto application is crash. I don't know if there is something wrong about the api connection handle or not. And could we do something to handle this?

![screenshot from 2018-08-08 17-20-36](https://user-images.githubusercontent.com/12755750/43871005-5315a47a-9b2f-11e8-9da8-d69490201be7.png)

As the screenshot above shows, the first five post operation is on 'continuing without db connection', which lead to pluto 'think' the connection is success, then cause a crash. Later on when i launch server, it works fine.

**Comment by samgomena** [comment]
Continuing without opening a connection to mongo was expected behavior. Just a heads up, the server's been updated to shutdown if a connection to mongo cannot be made.
