### ISSUE TITLE
fail to load pricing scheme within job interface

### ISSUE THREAD

**Issue by lixphilosophy** [shared-systems/api#7]
invalid endpoint Api("/pricing")

Please notice me if the endpoint change, so that i can update the frontend code to load time slot pricing on the application

**Comment by susham** [comment]
Endpoint works correctly, somehow the values are not retrieved as expected.. Currently debugging the code.

**Comment by susham** [comment]
API services generate the date in the format: 2018-08-10T07:00:00.000Z, whereas the date format stored in the database is: 2018-08-09T00:00:01.813Z

Not sure about the format stored in the mongodb

**Comment by samgomena** [comment]
I just pushed an update. It should fix this issue. I'm going to close this for now but please re-open if you run into any trouble with it.

**Comment by susham** [comment]
Able to test the fix and its fixed
